# Generated by Django 2.0.4 on 2018-05-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZZB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('day1class1', models.BooleanField(default=False)),
            ],
        ),
    ]
