# Generated by Django 2.0.4 on 2018-05-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0002_zzb'),
    ]

    operations = [
        migrations.AddField(
            model_name='zzb',
            name='day1class2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day1class3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day1class4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day2class1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day2class2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day2class3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day2class4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day3class1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day3class2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day3class3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day3class4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day4class1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day4class2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day4class3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day4class4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day5class1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day5class2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day5class3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zzb',
            name='day5class4',
            field=models.BooleanField(default=False),
        ),
    ]
