# Generated by Django 2.0.4 on 2018-05-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cls', '0003_auto_20180512_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zzb',
            name='day5class4',
        ),
    ]
